'use client';
import {ActivityHistory,type ActivitySource} from '../../activity';
import {type Activity} from '@/lib/activity';
const examples:Activity[]=[
  {id:'example-1',occurred_at:'2026-09-29T18:42:06Z',occurred_on:'2026-09-29',actor_id:'daniel',actor_name:'Daniel Bernal Yáñez',actor_email:'daniel@example.com',entity_type:'catalog',entity_id:'panel-demo',entity_label:'Panel fotovoltaico · Ejemplo 585 W',action:'price_changed',changes:[{field:'price',before:95000,after:102000}]},
  {id:'example-2',occurred_at:'2026-09-29T17:18:32Z',occurred_on:'2026-09-29',actor_id:'carol',actor_name:'Carol Ibaceta Durán',actor_email:'carol@example.com',entity_type:'client',entity_id:'client-demo',entity_label:'Cliente de demostración',action:'updated',changes:[{field:'address',before:'Calle de ejemplo 100',after:'Calle de ejemplo 120'},{field:'commune',before:'Santiago',after:'Ñuñoa'}]},
  {id:'example-3',occurred_at:'2026-09-29T15:06:10Z',occurred_on:'2026-09-29',actor_id:'marcelo',actor_name:'Marcelo González Muñoz',actor_email:'marcelo@example.com',entity_type:'quote',entity_id:'quote-demo',entity_label:'SOL-EJEMPLO-0042',action:'sent',changes:[{field:'sent_channel',before:null,after:'WhatsApp'},{field:'sent_on',before:null,after:'2026-09-29'}]},
  {id:'example-4',occurred_at:'2026-09-28T19:30:15Z',occurred_on:'2026-09-28',actor_id:'dev',actor_name:'Dev',actor_email:'dev@example.com',entity_type:'member',entity_id:'member-demo',entity_label:'Usuario de demostración',action:'updated',changes:[{field:'role',before:'pending',after:'admin'}]},
  {id:'example-5',occurred_at:'2026-09-28T16:10:01Z',occurred_on:'2026-09-28',actor_id:'nidia',actor_name:'Nidia Alonso Catalán',actor_email:'nidia@example.com',entity_type:'company',entity_id:'true',entity_label:'Configuración de la empresa',action:'updated',changes:[{field:'validDays',before:15,after:30}]},
];
const source:ActivitySource=async filters=>{const rows=examples.filter(e=>(!filters.actor||e.actor_name.toLocaleLowerCase('es').includes(filters.actor.toLocaleLowerCase('es')))&&(!filters.kind||e.entity_type===filters.kind)&&(!filters.action||e.action===filters.action)&&(!filters.from||e.occurred_on>=filters.from)&&(!filters.to||e.occurred_on<=filters.to));return {events:rows.slice(filters.offset,filters.offset+50),total:rows.length};};
export default function ActivityPreview(){return <main className="qh-preview"><div className="qh-preview-note"><strong>Revisión local · actividad de ejemplo</strong><span>Datos ficticios. La migración todavía no está activada en producción.</span></div><header><p>Solvex Solar / Gestión comercial</p><h1>Historial de actividad</h1></header><ActivityHistory dataSource={source}/></main>;}
