import assert from 'node:assert/strict';
import {savingsBillComparison,automaticSavings,resolvedProjection,newProjection,publishedProjection,projectionContext} from '../lib/projection';
import {newEnergyInput,solarGenerationContext} from '../lib/energy';
import {calculate,newQuote,initialProducts,initialSettings,quoteSchema,mergeQuotePatch,type SavedQuote} from '../lib/quote';
import {persistentQuote} from '../lib/quote-persistence';
const energy={...newEnergyInput(),consumptionKwh:400,billingDays:30,latitude:-33.45,longitude:-70.66};
const input={...newQuote(),customer:{...newQuote().customer,bill:120000},energy};
const settings={...initialSettings,taxMode:'included' as const};
const q:SavedQuote={id:'qa',date:'2026-10-03',folio:'qa',input,settings,calculation:calculate(input,initialProducts,settings)};
q.input.energy={...energy,solarGeneration:{annualKwh:6000,context:solarGenerationContext(energy,q.calculation.kwp),retrievedAt:'2026-10-03T12:00:00Z',source:'PVGIS · ejemplo de prueba'}};
const p=newProjection();
let a=automaticSavings(q,p).result!;
assert.equal(a.monthlyGeneration,500);assert.equal(a.selfConsumed,350);assert.equal(a.monthlySavings,105000);assert.equal(a.exportCredit,0);
assert.equal(automaticSavings(q,{...p,exportRate:50}).result?.monthlySavings,112500);
assert.equal(automaticSavings(q,{...p,energyRate:200}).result?.monthlySavings,70000);
assert.equal(automaticSavings(q,{...p,nonEnergyCharges:20000}).result?.monthlySavings,87500);
assert.equal(automaticSavings(q,{...p,selfConsumptionPercent:0}).result?.monthlySavings,0);
a=automaticSavings(q,{...p,selfConsumptionPercent:100}).result!;
assert.equal(a.selfConsumed,a.monthlyConsumption);assert.ok(a.selfConsumed<500);
const longBill={...q,input:{...q.input,energy:{...q.input.energy!,billingDays:60}}};
assert.ok(automaticSavings(longBill,p).result!.selfConsumed<automaticSavings(q,p).result!.selfConsumed);
const offGrid={...q,input:{...q.input,system:'OFF GRID' as const}};
assert.equal(automaticSavings(offGrid,p).result,null);
assert.equal(automaticSavings(offGrid,{...p,energyRate:200,exportRate:100}).result?.monthlySavings,70000);
assert.equal(automaticSavings({...q,calculation:{...q.calculation,kwp:6}},p).result,null);
assert.equal(automaticSavings({...q,input:{...q.input,energy:{...q.input.energy!,tilt:15}}},p).result,null);
assert.equal(automaticSavings({...q,input:{...q.input,energy:{...q.input.energy!,latitude:-35}}},p).result,null);
assert.equal(mergeQuotePatch(q.input,{customer:{...q.input.customer,address:'Nueva dirección'}}).energy?.solarGeneration,undefined);
assert.equal(automaticSavings({...q,input:{...q.input,energy:undefined}},p).result,null);
assert.equal(automaticSavings({...q,input:{...q.input,energy:{...q.input.energy!,consumptionKwh:0}}},p).result,null);
assert.equal(automaticSavings(q,{...p,nonEnergyCharges:130000}).result,null);
assert.equal(resolvedProjection(q).monthlySavings,105000);
const manual={...p,savingsMode:'manual' as const,monthlySavings:115000,savingsSource:'Ajuste del equipo'};
assert.equal(resolvedProjection({...q,input:{...q.input,projection:manual}}).monthlySavings,115000);
const {savingsMode:_,...legacy}=manual;
assert.equal(resolvedProjection({...q,input:{...q.input,projection:legacy}}).monthlySavings,115000);
q.input.projection=resolvedProjection(q);q.input.projection.reviewedFor=projectionContext(q,q.input.projection);
assert.ok(publishedProjection(q));
const stored={...q,input:quoteSchema.parse(JSON.parse(JSON.stringify(q.input)))};
assert.ok(publishedProjection(stored));
assert.equal(publishedProjection({...q,input:{...q.input,customer:{...q.input.customer,bill:130000}}}),null);
assert.equal(publishedProjection({...q,calculation:{...q.calculation,kwp:6}}),null);
const googleEnergy={...q.input.energy!,googlePlaceId:'test-place'};
googleEnergy.solarGeneration={...googleEnergy.solarGeneration!,context:solarGenerationContext(googleEnergy,q.calculation.kwp)};
const google={...q,input:{...q.input,energy:googleEnergy}};
assert.equal(resolvedProjection({...google,input:persistentQuote(google.input)}).monthlySavings,105000);
assert.ok(!JSON.stringify(persistentQuote(google.input).energy).includes('-33.45'));
assert.equal(quoteSchema.safeParse({...q.input,projection:{...p,selfConsumptionPercent:101}}).success,false);
console.log('Ahorro automático: consumo, generación, IVA/tarifa editable, excedentes, Off Grid, edición, guardado y datos desactualizados: OK');
// Monthly comparisons must normalize 30/60-day bills and preserve manual values.
const comparison=savingsBillComparison(q,manual)!;
assert.equal(comparison.monthlyBill,120000/30*365/12);
assert.equal(comparison.percent,115000/comparison.monthlyBill*100);
assert.equal(savingsBillComparison(longBill,manual)!.monthlyBill,comparison.monthlyBill/2);
assert.equal(savingsBillComparison(offGrid,manual),null);
assert.equal(savingsBillComparison({...q,input:{...q.input,customer:{...q.input.customer,bill:0}}},manual),null);
assert.equal(savingsBillComparison({...q,input:{...q.input,energy:undefined}},manual),null);
assert.equal(savingsBillComparison(q,{...manual,monthlySavings:null}),null);
assert.equal(savingsBillComparison(q,{...manual,monthlySavings:0})!.percent,0);
const excess=savingsBillComparison(q,{...manual,monthlySavings:200000})!;
assert.ok(excess.percent>100);assert.equal(excess.barPercent,100);
