import assert from 'node:assert/strict';
import {geocodeGoogleAddress,googleAddressQuery,parseGoogleLocations,streetAddress} from '../lib/google-geocoding';
import {persistentQuote} from '../lib/quote-persistence';
import {newQuote,mergeQuotePatch} from '../lib/quote';
import {newEnergyInput} from '../lib/energy';
const input={address:'Av. La Dehesa 181 oficina 509. Lo Barnechea',commune:'Lo Barnechea',region:'Metropolitana de Santiago'};
const component=(long_name:string,type:string,short_name=long_name)=>({long_name,short_name,types:[type]});
const result={formatted_address:'Av. La Dehesa 181, Lo Barnechea, Región Metropolitana, Chile',place_id:'test-place',types:['street_address'],geometry:{location:{lat:-33.36,lng:-70.51},location_type:'ROOFTOP'},address_components:[component('Chile','country','CL'),component('Región Metropolitana','administrative_area_level_1'),component('Santiago','administrative_area_level_2'),component('Lo Barnechea','administrative_area_level_3'),component('Santiago','locality'),component('181','street_number')]};
const response=(results:unknown[])=>({status:'OK',results});
assert.equal(streetAddress(input.address),'Av. La Dehesa 181. Lo Barnechea');
assert.ok(!googleAddressQuery(input).includes('509'));
assert.throws(()=>googleAddressQuery({...input,commune:'Santiago'}),/La dirección indica Lo Barnechea/);
assert.equal(parseGoogleLocations(response([result,result]),input).length,1);
assert.equal(parseGoogleLocations(response([result]),input)[0].approximate,false);
assert.equal(parseGoogleLocations(response([{...result,partial_match:true}]),input)[0].approximate,true);
assert.equal(parseGoogleLocations(response([{...result,geometry:{...result.geometry,location_type:'RANGE_INTERPOLATED'}}]),input)[0].approximate,true);
assert.deepEqual(parseGoogleLocations(response([{...result,types:['locality','political']}]),input),[]);
assert.deepEqual(parseGoogleLocations(response([{...result,geometry:{...result.geometry,location:{lat:0,lng:0}}}]),input),[]);
assert.deepEqual(parseGoogleLocations(response([{...result,address_components:[component('Argentina','country','AR')]}]),input),[]);
assert.deepEqual(parseGoogleLocations({status:'ZERO_RESULTS'},input),[]);
assert.throws(()=>parseGoogleLocations(response([result]),{...input,commune:'Santiago'}),/en Lo Barnechea/);
assert.throws(()=>parseGoogleLocations({status:'REQUEST_DENIED',error_message:'secret upstream detail'},input),e=>e instanceof Error&&!e.message.includes('secret'));
assert.throws(()=>parseGoogleLocations({status:'OVER_QUERY_LIMIT'},input),/límite/);
const quote={...newQuote(),energy:{...newEnergyInput(),latitude:-33.36,longitude:-70.51,googlePlaceId:'test-place'}};
assert.equal(persistentQuote(quote).energy?.latitude,null);
assert.equal(persistentQuote(quote).energy?.googlePlaceId,'test-place');
assert.equal(quote.energy.latitude,-33.36);
assert.equal(persistentQuote({...quote,energy:{...quote.energy,googlePlaceId:undefined}}).energy?.latitude,-33.36);
assert.equal(mergeQuotePatch(quote,{customer:{...quote.customer,address:'Otra 22'}}).energy?.googlePlaceId,undefined);
async function run(){
 let calls=0;
 const fetcher=(async(url,options)=>{calls++;const u=new URL(String(url));assert.equal(u.origin,'https://maps.googleapis.com');assert.equal(u.searchParams.get('components'),'country:CL');assert.equal(u.searchParams.get('key'),'test-key');assert.equal(options?.cache,'no-store');assert.equal(u.searchParams.get('address')?.includes('509'),false);return Response.json(response([result]))}) as typeof fetch;
 const found=await geocodeGoogleAddress(input,'test-key',fetcher);assert.equal(found[0].placeId,'test-place');assert.equal(calls,1);
 await assert.rejects(()=>geocodeGoogleAddress(input,undefined,fetcher),/pendiente de configuración/);assert.equal(calls,1);
 await assert.rejects(()=>geocodeGoogleAddress({...input,commune:'Santiago'},'test-key',fetcher),/Corrige la comuna/);assert.equal(calls,1);
 await assert.rejects(()=>geocodeGoogleAddress(input,'test-key',(async()=>{throw Error('URL with secret')}) as typeof fetch),e=>e instanceof Error&&!e.message.includes('secret'));
 console.log('Google geocoding: address, commune, precision, failure handling, privacy and persistence: OK');
}
void run();
