import assert from 'node:assert/strict';
import {memberColors,memberColor,colorRequestSchema,resolveResponsibleColor} from '../lib/member-color';
import {quotePersonColor,type HistoryQuote} from '../lib/quote-history';
import {activityValue} from '../lib/activity';
assert.equal(memberColor('violet','any').id,'violet');
assert.equal(memberColor(null,'dev').id,'blue','Expanding the palette must preserve existing automatic colors');
assert.equal(colorRequestSchema.safeParse({color:'copper'}).success,true);
assert.equal(memberColor('copper','dev').id,'copper');
assert.equal(memberColors[quotePersonColor({responsibleColor:'copper'} as HistoryQuote)].id,'copper');
const luminance=(hex:string)=>{const c=hex.slice(1).match(/../g)!.map(v=>parseInt(v,16)/255).map(v=>v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];};
for(const color of memberColors)assert.ok((luminance(color.background)+.05)/(luminance(color.foreground)+.05)>=4.5,`${color.name} label must remain readable`);
assert.deepEqual(memberColor(null,'dev'),memberColor(undefined,'dev'));
assert.equal(colorRequestSchema.safeParse({color:'red'}).success,false);
assert.equal(colorRequestSchema.safeParse({color:'#ffffff'}).success,false);
assert.equal(colorRequestSchema.safeParse({color:'blue',id:'another-user'}).success,false);
assert.equal(colorRequestSchema.safeParse({color:'blue',role:'admin'}).success,false);
assert.equal(colorRequestSchema.safeParse({color:null}).success,true);
const owner={id:'dev',identification_color:'violet'};
const members=[{id:'daniel',email:'Daniel@Example.com',identification_color:'amber'}];
assert.equal(resolveResponsibleColor(undefined,owner,members),'violet');
assert.equal(resolveResponsibleColor(' daniel@example.com ',owner,members),'amber');
assert.equal(resolveResponsibleColor('other@example.com',owner,members),null,'Never use the author color for a different adviser');
assert.equal(resolveResponsibleColor('',owner,members),null);
assert.equal(resolveResponsibleColor('daniel@example.com',owner,[...members,...members]),null,'Ambiguous email must not guess');
assert.equal(resolveResponsibleColor(undefined,{id:'dev'},[]),memberColor(null,'dev').id);
assert.equal(quotePersonColor({responsibleColor:'rose'} as HistoryQuote),4);
assert.equal(activityValue('identification_color','violet'),'Violeta');
assert.equal(activityValue('identification_color',null),'Automático');
console.log('Colores personales: validación, identidad, etiquetas y auditoría: OK');
