import assert from 'node:assert/strict';
import {workflowReadiness} from '../lib/workflow';
import {calculate,newQuote,initialProducts,initialSettings} from '../lib/quote';
import {managementSummary} from '../lib/management-dashboard';
import {quoteGroups,followupSchema} from '../lib/followup';
import type {HistoryQuote} from '../lib/quote-history';
const q={...newQuote(),customer:{name:'QA',email:'qa@example.com',phone:'+56900000000',region:'Metropolitana',commune:'Santiago',address:'',bill:0}};
const calculation=calculate(q,initialProducts,initialSettings);
assert.equal(workflowReadiness(q,initialProducts,calculation).customer,true,'Preliminary can progress without a bill');
assert.equal(workflowReadiness({...q,proposalType:'final'},initialProducts,calculation).customer,false,'Final requires reviewed consumption');
assert.equal(calculation.official,false,'Preliminary progression must not validate missing energy data');
assert.equal(workflowReadiness(q,initialProducts,calculation,[]).installation,false,'Use current configured rates');
const base:HistoryQuote={id:'root',projectId:'root',date:'2026-09-12T15:00:00Z',folio:'A',input:q,settings:initialSettings,calculation:{...calculation,complete:true,total:100},sentOn:'2026-09-12'};
const second={...base,id:'revision',date:'2026-09-14T15:00:00Z',sentOn:'2026-09-14',calculation:{...base.calculation,total:150}};
const pending={...second,id:'pending',date:'2026-09-15T15:00:00Z',sentOn:null};
assert.deepEqual(quoteGroups([base,second,pending])[0].map(q=>q.id),['pending','revision','root']);
const summary=managementSummary([base,second,pending],'2026-09');assert.equal(summary.created,1);assert.equal(summary.sent,1);assert.equal(summary.amount,150);assert.equal(summary.pending,0);
assert.equal(managementSummary([base,{...second,date:'2026-10-02T15:00:00Z',sentOn:'2026-10-02'}],'2026-10').created,0,'Revision does not become a new project');
assert.equal(followupSchema.safeParse({status:'accepted',next_contact:'2026-02-30',expected:null}).success,false);
assert.equal(followupSchema.safeParse({status:'followup',next_contact:'2026-10-10',expected:null}).success,true);
console.log('Productivity: preliminary/final, configured rates, project revisions, amounts and dates passed.');
