import assert from 'node:assert/strict';
import {newProjection,calculateProjection,projectionContext,publishedProjection} from '../lib/projection';
import {newQuote,initialSettings,quoteSchema,type SavedQuote} from '../lib/quote';
const p={...newProjection(),monthlySavings:100000,savingsSource:'Estudio técnico QA',degradation:0,years:10};
let r=calculateProjection(p,6000000)!;
assert.equal(r.payback,5);assert.equal(r.cumulative,12000000);assert.equal(r.net,6000000);assert.equal(r.co2Tonnes,null);
r=calculateProjection({...p,annualMaintenance:200000,replacementYear:5,replacementCost:2000000},6000000)!;
assert.equal(r.cumulative,8000000);assert.equal(r.payback,8);
assert.equal(calculateProjection({...p,monthlySavings:0},6000000),null);
assert.equal(calculateProjection({...p,years:0},6000000),null);
assert.equal(calculateProjection({...p,replacementCost:1,replacementYear:20},6000000),null);
assert.equal(calculateProjection({...p,emissionFactor:0.4},6000000),null);
assert.equal(calculateProjection({...p,avoidedKwh:6000,emissionFactor:0.4,emissionSource:'Factor sintético QA'},6000000)?.co2Tonnes,2.4);
assert.equal(calculateProjection({...p,annualMaintenance:1200001},6000000)?.payback,null);
assert.equal(calculateProjection({...p,monthlySavings:105000},7300000)?.payback,7300000/1260000);
const q:SavedQuote={id:'QA',folio:'QA',date:'2026-10-02',input:{...newQuote(),projection:p},settings:initialSettings,calculation:{lines:[],panels:8,kwp:4.68,subtotal:6000000,discount:0,net:6000000,tax:0,total:6000000,warnings:[],complete:true,official:false}};
assert.equal(publishedProjection(q),null);
q.input.projection={...p,reviewedFor:projectionContext(q,p)};
assert.ok(publishedProjection(q));assert.ok(quoteSchema.parse(q.input).projection?.reviewedFor);
assert.equal(publishedProjection({...q,calculation:{...q.calculation,total:7000000}}),null);
assert.equal(publishedProjection({...q,input:{...q.input,customer:{...q.input.customer,address:'Otra dirección'}}}),null);
assert.equal(publishedProjection({...q,input:{...q.input,projection:{...q.input.projection,monthlySavings:110000}}}),null);
assert.equal(publishedProjection({...q,calculation:{...q.calculation,complete:false}}),null);
console.log('Proyección, costos, emisiones, validación y snapshots: OK');
