import assert from 'node:assert/strict';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AtlasProposal} from '../app/atlas-proposal';
import {PDFDocument} from 'pdf-lib';
import {newQuote,initialProducts,initialSettings,calculate,quoteSchema,money,type SavedQuote} from '../lib/quote';
import {proposalLayout,usesAtlasProposal} from '../lib/proposal-layout';
import {proposalCanvases} from '../lib/proposal-canvas';
import {newProposalContent} from '../lib/proposal-content';
import {customerDocumentSettings,paymentBreakdown} from '../lib/commercial';
import {persistentQuote} from '../lib/quote-persistence';
import {quotePdf} from '../lib/pdf';
import {newProjection,projectionContext} from '../lib/projection';

async function run(){
 const input={...newQuote(),customer:{...newQuote().customer,name:'Cliente de ejemplo',email:'privado@example.com',phone:'+56911111111',commune:'Santiago'},notes:'Incluye suministro e instalación. No incluye refuerzo estructural.'};
 const settings={...initialSettings,taxMode:'included' as const,warranty:'Garantías sujetas al fabricante y al alcance acordado.',terms:'Propuesta válida por 15 días.',paymentSchedule:[{label:'Anticipo',percent:20},{label:'Inicio',percent:30},{label:'Entrega',percent:50}]};
 const q:SavedQuote={id:'test',folio:'SVX-2026-000123',date:'2026-10-06T15:00:00Z',issuedAt:'2026-10-06T15:00:00Z',input,settings,calculation:calculate(input,initialProducts,settings)};
 const frozen=JSON.stringify(q);
 const original=proposalLayout(q);
 assert.ok(!JSON.stringify(original).includes(input.customer.email));assert.ok(!JSON.stringify(original).includes(input.customer.phone));
 assert.ok(!original.some(p=>p.id==='visualization'),'No incluir hoja de croquis eliminada en el referente');
 assert.equal(usesAtlasProposal(q),true);
 assert.equal(usesAtlasProposal({...q,input:{...input,proposalContent:undefined}}),false,'Conservar salida de cotizaciones antiguas emitidas');
 assert.equal(usesAtlasProposal({...q,issuedAt:undefined,input:{...input,proposalContent:undefined}}),false,'Un borrador antiguo conserva el mismo diseño antes y después de emitir');
 const edited=quoteSchema.parse({...input,finalTotalOverride:5155000,documentPaymentSchedule:[{label:'Reserva',percent:40},{label:'Recepción',percent:60}],proposalContent:{...newProposalContent(),text:{'cover:title':'Proyecto solar para tu hogar','scope:body':'Texto editado con ñ y <script>alert(1)</script>','equipment-0:value':'Panel de prueba 600 W'},hidden:['technical'],order:['cover','investment-page','equipment','custom-test'],sections:[{id:'test',title:'Acuerdos adicionales',body:'Una sección nueva.'},{id:'onsite',pageId:'equipment',title:'Visita',body:'Coordinar acceso al inmueble.'}]}});
 const reopened=quoteSchema.parse(JSON.parse(JSON.stringify(persistentQuote(edited))));
 const changed={...q,input:reopened,calculation:calculate(reopened,initialProducts,settings)};
 assert.equal(changed.calculation.total,5155000);
 const pages=proposalLayout(changed),all=JSON.stringify(pages);
 assert.equal(pages[0].title,'Proyecto solar para tu hogar');assert.equal(pages[1].id,'investment-page');
 assert.ok(all.includes('Una sección nueva.'));assert.ok(all.includes('Coordinar acceso al inmueble.'));assert.ok(!all.includes('Antes de la cotización final'));
 assert.ok(proposalLayout(changed,true).some(p=>p.blocks.some(b=>b.id==='technical')),'Se puede restaurar un bloque oculto');
 const payments=paymentBreakdown(changed.calculation.total,customerDocumentSettings(reopened,settings));
 assert.deepEqual(payments.map(p=>p.amount),[2062000,3093000]);
 const canvases=proposalCanvases(changed);
 assert.ok(canvases.flatMap(p=>p.ops).some(op=>op.kind==='text'&&op.text===money(5155000)));
 assert.ok(canvases.flatMap(p=>p.ops).some(op=>op.kind==='text'&&op.text.includes('<script>')),'El texto es dato, nunca HTML ejecutable');
 const html=renderToStaticMarkup(createElement(AtlasProposal,{q:changed}));
 assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'),'Escapar contenido editable en HTML');
 assert.equal((html.match(/<svg /g)??[]).length,canvases.length);
 const pdf=await PDFDocument.load(await quotePdf(changed));
 assert.equal(pdf.getPageCount(),canvases.length,'HTML y PDF tienen las mismas páginas');
 assert.ok(pdf.getPages().every(p=>p.getWidth()===842&&p.getHeight()===595),'PDF horizontal');
 const long={...changed,input:{...reopened,proposalContent:{...reopened.proposalContent!,text:{...reopened.proposalContent!.text,'scope:body':('Alcance extenso con instalación, pruebas y puesta en servicio.\n').repeat(160)}}}};
 const longPages=proposalCanvases(long);
 assert.ok(longPages.length>canvases.length,'Paginar contenido agregado sin cortarlo');
 for(const page of longPages)for(const op of page.ops)if(op.kind==='text')assert.ok(op.y<=577&&op.y>0,`Texto fuera de página ${op.text}`);
 const projection={...newProjection(),savingsMode:'manual' as const,monthlySavings:100000,savingsSource:'Supuesto de prueba validado'};
 const projected={...changed,input:{...changed.input,projection}};
 projection.reviewedFor=projectionContext(projected,projection);
 assert.ok(proposalLayout(projected).some(p=>p.id==='analysis'));
 const lengthy={...projected,input:{...projected.input,proposalContent:{...projected.input.proposalContent!,text:{...projected.input.proposalContent!.text,...Object.fromEntries(['analysis','investment-page','equipment','cover'].flatMap(id=>[[`${id}:title`,'W'.repeat(200)],[`${id}:subtitle`,'W'.repeat(500)]])),'chart:title':'W'.repeat(200),'assumptions:title':'W'.repeat(200)}}}};
 for(const page of proposalCanvases(lengthy))for(const op of page.ops)if(op.kind==='text')assert.ok(op.y<=577&&op.y>0,`Título largo fuera de página ${page.id}: ${op.y}`);
 assert.ok(!proposalLayout({...projected,calculation:{...projected.calculation,total:6000000}}).some(p=>p.id==='analysis'),'No publicar ahorro sin revalidar después de cambiar inversión');
 assert.equal(JSON.stringify(q),frozen,'No modificar la cotización emitida original');
 assert.equal(quoteSchema.safeParse({...input,documentPaymentSchedule:[{label:'Único',percent:90}]}).success,false);
 assert.equal(quoteSchema.safeParse({...input,proposalContent:{...newProposalContent(),text:{'cover:title':'a'.repeat(201)}}}).success,false);
 assert.equal(quoteSchema.safeParse({...input,proposalContent:{...newProposalContent(),sections:[{id:'x',title:'a',body:'b'},{id:'x',title:'c',body:'d'}]}}).success,false);
 console.log('Editor: textos, números, páginas, ocultar/restaurar, persistencia, IVA/pagos, proyección, PDF horizontal y paginación: OK');
}
void run();
