import assert from 'node:assert/strict';
import {calculate,newQuote,initialProducts,initialSettings,productSchema,reconcileQuoteProducts} from '../lib/quote';
initialProducts.forEach(p=>productSchema.parse(p));
const q=newQuote(); const a=calculate(q,initialProducts,initialSettings);
assert.equal(a.panels,8); assert.equal(a.official,false); assert.equal(a.tax,null);
assert.ok(a.lines.some(l=>l.category==='PANEL FOTOVOLTAICO'&&l.total!>0));
const discounted=calculate({...q,discountPercent:undefined,discount:10000},initialProducts,initialSettings);
assert.equal(a.total-discounted.total,10000);
const missing=calculate({...q,quantities:{...q.quantities,'0-10':11}},initialProducts,initialSettings);
assert.equal(missing.complete,false);
const invalid=calculate({...q,discountPercent:undefined,discount:1e10},initialProducts,initialSettings);
assert.equal(invalid.complete,false);
const customRates=calculate(q,initialProducts,initialSettings,[{panels:8,price:123456,source:'Tarifa sintética de base de datos'}]);
assert.equal(customRates.lines.find(l=>l.id==='installation')?.total,123456);
console.log('Pruebas del catálogo de demostración: OK');
const original={...newQuote(),technicalReviewed:true,hiddenLineIds:['0-10','installation','extra']};
const frozenSnapshot=JSON.stringify(original),storedCalculation=JSON.stringify(calculate(original,initialProducts,initialSettings));
const remaining=initialProducts.filter(p=>p.id!=='0-10');
const cleaned=reconcileQuoteProducts(original,remaining);
assert.equal(cleaned.quantities['0-10'],undefined);
assert.equal(cleaned.technicalReviewed,false);
assert.deepEqual(cleaned.hiddenLineIds,['installation','extra']);
assert.equal(cleaned.quantities['0-13'],0,'Sin paneles, estructura se recalcula');
assert.equal(calculate(cleaned,remaining,initialSettings).complete,false,'Debe revisar y elegir panel de reemplazo');
assert.equal(JSON.stringify(original),frozenSnapshot,'La cotización original no se modifica');
assert.equal(JSON.stringify(calculate(original,initialProducts,initialSettings)),storedCalculation);
assert.throws(()=>calculate(original,remaining,initialSettings),/ya no está en el catálogo/,'El servidor sigue rechazando equipos retirados');
assert.equal(reconcileQuoteProducts(original,initialProducts),original,'Sin eliminaciones no cambia la revisión');
assert.doesNotThrow(()=>calculate(reconcileQuoteProducts(newQuote(),remaining),remaining,initialSettings),'Un nuevo borrador no vuelve a seleccionar equipos eliminados');
console.log('Eliminar equipo: borradores, totales, revisión e historial conservado: OK');
