import assert from 'node:assert/strict';
import {newQuote,calculate,initialProducts,initialSettings,type SavedQuote} from '../lib/quote';
import {documentTitle,isIssued,issuanceProblems} from '../lib/quote-issuance';
const input={...newQuote(),customer:{...newQuote().customer,name:'Cliente prueba',email:'prueba@example.com'}};
const settings={...initialSettings,taxMode:'included' as const};
const draft:SavedQuote={id:'draft',folio:'BORRADOR-SVX',date:'2026-10-02T12:00:00Z',input,settings,calculation:calculate(input,initialProducts,settings)};
assert.deepEqual(issuanceProblems(draft),[],'Una propuesta preliminar completa puede emitirse, manteniendo sus condiciones técnicas');
assert.equal(documentTitle(draft),'PRECOTIZACIÓN');
const issued={...draft,id:'persisted',folio:'SVX-2026-000001',issuedAt:'2026-10-03T00:15:00Z'};
assert.equal(isIssued(issued),true);
assert.equal(documentTitle(issued),'COTIZACIÓN');
assert.equal(issued.calculation.official,false,'Emitir no inventa una aprobación técnica');
assert.equal(isIssued({...issued,folio:'BORRADOR-SVX'}),false);
assert.equal(isIssued({...issued,issuedAt:undefined}),false);
assert.ok(issuanceProblems({...draft,calculation:{...draft.calculation,complete:false}}).length);
assert.ok(issuanceProblems({...draft,settings:initialSettings}).length);
assert.ok(issuanceProblems({...draft,input:{...input,customer:{...input.customer,name:''}}}).length);
assert.ok(issuanceProblems({...draft,input:{...input,proposalType:'final'}}).length,'No se emite una propuesta final con validaciones pendientes');
assert.deepEqual(issuanceProblems({...draft,input:{...input,proposalType:'final'},calculation:{...draft.calculation,official:true}}),[]);
console.log('Emisión: título, folio, validaciones y aprobación técnica independiente: OK');
