import assert from 'node:assert/strict';
import {calculate,newQuote,initialProducts,initialSettings,type SavedQuote} from '../lib/quote';
import {quoteValidationIssues} from '../lib/quote-validation';
import {issuanceProblems} from '../lib/quote-issuance';
import {newEnergyInput} from '../lib/energy';
const settings={...initialSettings,taxMode:'included' as const,legal:'Empresa de prueba',rut:'Prueba',terms:'Condiciones de prueba',warranty:'Garantía de prueba',approved:true};
const input={...newQuote(),proposalType:'final' as const};
function snapshot(value=input,company=settings,products=initialProducts):SavedQuote{return {id:'draft',folio:'BORRADOR-SVX',date:'',input:value,settings:company,calculation:calculate(value,products,company)}}
const missing=quoteValidationIssues(snapshot());
for(const id of ['customer-name','customer-email','customer-phone','customer-region','customer-commune','customer-bill','consumption','billing-days','bill-review','technical'])assert.ok(missing.some(i=>i.id===id),id);
assert.equal(missing.find(i=>i.id==='technical')?.step,'review');
assert.equal(missing.find(i=>i.id==='customer-commune')?.field,'Región','A disabled commune selector must route to its prerequisite');
assert.equal(new Set(missing.map(i=>i.id)).size,missing.length);
const complete={...input,technicalReviewed:true,customer:{...input.customer,name:'Cliente prueba',email:'prueba@example.com',phone:'+56900000000',region:'Metropolitana de Santiago',commune:'Santiago',bill:50000},energy:{...newEnergyInput(),consumptionKwh:300,billingDays:30,billReviewed:true}};
assert.deepEqual(quoteValidationIssues(snapshot(complete)),[]);
assert.deepEqual(issuanceProblems(snapshot(complete)),[]);
const withoutName={...complete,customer:{...complete.customer,name:''}};
assert.deepEqual(quoteValidationIssues(snapshot(withoutName)).map(i=>i.id),['customer-name'],'Fixing fields removes only the resolved errors');
const prelim={...complete,proposalType:'preliminary' as const,technicalReviewed:false,energy:undefined,customer:{...input.customer,name:'Cliente prueba',phone:'+56900000000'}};
const preliminary:SavedQuote={...snapshot(),input:prelim,calculation:calculate(prelim,initialProducts,settings)};
assert.deepEqual(quoteValidationIssues(preliminary),[],'Do not impose final-quote requirements on a preliminary quote');
const incompleteCompany={...settings,approved:false,legal:'',rut:'',terms:'',warranty:'',taxMode:'pending' as const};
const companyIssues=quoteValidationIssues({...snapshot(complete),settings:incompleteCompany,calculation:calculate(complete,initialProducts,incompleteCompany)});
for(const id of ['tax','settings-legal','settings-rut','settings-terms','settings-warranty','settings-approved'])assert.equal(companyIssues.find(i=>i.id===id)?.tab,'settings',id);
const manual={...complete,installationOverride:700000,installationNote:''};
assert.equal(quoteValidationIssues(snapshot(manual)).find(i=>i.id==='installation-note')?.field,'Motivo y aprobación');
const unpriced=initialProducts.map(p=>p.id==='0-10'?{...p,price:null,watts:null}:p);
const priceIssues=quoteValidationIssues(snapshot(complete,settings,unpriced));
assert.equal(priceIssues.find(i=>i.id==='price-0-10')?.productId,'0-10');
assert.equal(priceIssues.find(i=>i.id==='watts-0-10')?.field,'Potencia (Wp)');
const custom={...complete,customServices:[{id:'958ba04e-d99f-4a37-8614-f6a92d6a1591',name:'',quantity:1,price:null}]};
const customIssues=quoteValidationIssues(snapshot(custom));
assert.ok(customIssues.some(i=>i.field==='Descripción del servicio adicional 1'));
assert.ok(customIssues.some(i=>i.field==='Precio del servicio adicional 1'));
const noRate={...snapshot(complete),calculation:calculate(complete,initialProducts,settings,[])};
assert.equal(quoteValidationIssues(noRate).find(i=>i.id==='installation-rate')?.step,'installation');
const historical={...snapshot(complete),id:'saved-version'};
const original=JSON.stringify(historical);quoteValidationIssues(historical);assert.equal(JSON.stringify(historical),original,'Guidance never mutates a saved quote');
console.log('Validaciones: detalle por campo, destinos, dependencias, corrección, tarifas, catálogo y requisitos de cotización final: OK');
