'use client';
import {useState} from 'react';
import {readRecovery,writeRecovery,saveDraft} from '@/lib/local-recovery';
import {backupBills,type BillBackupJob} from '@/lib/bill-backup';
const key='qa-recovery-isolated';
export default function RecoveryTest(){const [message,setMessage]=useState('Prueba local aislada. Solo usa documentos sintéticos.');
 async function prepare(){try{await writeRecovery(key,undefined);const files=[1,2,3].map(n=>new File([`%PDF-1.7\nsynthetic-${n}`],`qa-${n}.pdf`,{type:'application/pdf'}));const job:BillBackupJob={quoteId:'qa',folio:'QA',ownerId:'synthetic',files,completed:1};await writeRecovery(key,job);const version=await saveDraft(key+'-draft',{text:'Draft preserved'},null);let conflict=false;try{await saveDraft(key+'-draft',{text:'Unexpected overwrite'},null)}catch{conflict=true}if(!conflict)throw Error('Conflict was not rejected');const unchanged=await readRecovery<{version:string}>(key+'-draft');if(unchanged?.version!==version)throw Error('Existing draft was overwritten');setMessage('Preparado: 3 archivos y conflicto entre pestañas comprobado. Recarga esta página y verifica la recuperación.')}catch(e){setMessage('ERROR: '+(e as Error).message)}}
 async function verify(){try{const job=await readRecovery<BillBackupJob>(key);if(!job||job.files.length!==3||job.completed!==1)throw Error('Missing saved backup');for(let i=0;i<3;i++)if(await job.files[i].text()!==`%PDF-1.7\nsynthetic-${i+1}`)throw Error('Bytes changed');const uploaded:string[]=[];await backupBills(job,{upload:async path=>{uploaded.push(path)},download:async()=>{throw Error('Not expected')}},async()=>writeRecovery(key,job));if(uploaded.length!==2||uploaded.some(p=>p.endsWith('/frente')))throw Error('Wrong resume position');await writeRecovery(key,undefined);await writeRecovery(key+'-draft',undefined);setMessage('PASS: 3 archivos intactos tras recargar, borrador protegido y respaldo retomado desde el segundo archivo.')}catch(e){setMessage('ERROR: '+(e as Error).message)}}
 return <main style={{padding:40,fontFamily:'sans-serif'}}><h1>Verificación de recuperación</h1><button onClick={()=>void prepare()}>Preparar archivos sintéticos</button><button onClick={()=>void verify()}>Verificar tras recargar</button><p role="status">{message}</p></main>}
