"use client";
import {useMemo,useState} from 'react';
import {Plus,Save,Search,Pencil,Package,Check,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {money,productUnit,isInstallation,productSchema,systems,systemNames,type Product} from '@/lib/quote';

const categoryLabel=(s:string)=>s.toLocaleLowerCase('es').replace(/^./,c=>c.toUpperCase());
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');
type Props={products:Product[];dirty:boolean;busy:boolean;loaded:boolean;canEdit:boolean;demo:boolean;onApply:(product:Product)=>void;onSave:()=>void};
export function EquipmentCatalog({products,dirty,busy,loaded,canEdit,demo,onApply,onSave}:Props){
 const [system,setSystem]=useState<Product['system']>('ON GRID'),[search,setSearch]=useState(''),[category,setCategory]=useState('');
 const [draft,setDraft]=useState<Product|null>(null),[isNew,setIsNew]=useState(false),[error,setError]=useState('');
 const systemProducts=useMemo(()=>products.filter(p=>p.system===system),[products,system]);
 const categories=useMemo(()=>Array.from(new Set(systemProducts.map(p=>p.category))).sort((a,b)=>a.localeCompare(b,'es')),[systemProducts]);
 const allCategories=useMemo(()=>Array.from(new Set([...products.map(p=>p.category),'SERVICIOS'])).sort((a,b)=>a.localeCompare(b,'es')),[products]);
 const filtered=systemProducts.filter(p=>(!category||p.category===category)&&normalize(p.name+' '+p.category+' '+p.unit).includes(normalize(search)));
 function open(product?:Product){setError('');setIsNew(!product);setDraft(product?{...product}:{id:crypto.randomUUID(),system,category:'SERVICIOS',name:'',price:null,watts:null,unit:'unidad',source:'Ingreso manual'})}
 function apply(){if(!draft||!canEdit||busy)return;const result=productSchema.safeParse({...draft,name:draft.name.trim(),category:draft.category.trim().toLocaleUpperCase('es'),unit:draft.unit.trim(),source:draft.source.trim()});if(!result.success){setError('Revisa nombre, categoría y unidad. El precio debe ser positivo o cero y la potencia no puede superar 2.000 Wp.');return}if(isInstallation(result.data)&&products.some(p=>p.id!==result.data.id&&p.system===result.data.system&&isInstallation(p))){setError('Ya existe una tarifa de instalación para este sistema. Edita esa ficha.');return}onApply({...result.data,unit:productUnit(result.data)});setSystem(result.data.system);setCategory('');setSearch('');setDraft(null)}
 return <section className="equipment-catalog" aria-label="Catálogo de equipos y servicios">
  <header className="equipment-header"><div className="equipment-heading"><span className="equipment-symbol"><Package size={25}/></span><div><h2>Catálogo de equipos y servicios</h2><p>Consulta los valores y mantén actualizada cada ficha.</p></div></div><div className="equipment-actions">{canEdit&&<><Button variant="outline" disabled={busy} onClick={()=>open()}><Plus size={18}/>Agregar equipo</Button><Button disabled={!dirty||busy||!loaded} onClick={onSave}><Save size={18}/>{busy?'Guardando…':'Guardar catálogo'}</Button></>}</div></header>
  <div className="equipment-status"><span className={dirty?'equipment-save-state is-pending':'equipment-save-state'} role="status">{dirty?<Pencil size={15}/>:<Check size={16}/>} {dirty?'Cambios pendientes de guardar':demo?'Catálogo de demostración':'Sin cambios pendientes'}</span><p>{demo?'Valores ficticios para demostración. ':''}Guarda para compartir los cambios con el equipo. Las cotizaciones anteriores conservan sus valores.</p></div>
  <div className="equipment-filters"><label>Sistema<select value={system} onChange={e=>{setSystem(e.target.value as Product['system']);setCategory('')}}>{systems.map(s=><option value={s} key={s}>{systemNames[s]}</option>)}</select></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas las categorías</option>{categories.map(c=><option value={c} key={c}>{categoryLabel(c)}</option>)}</select></label><label>Buscar en el catálogo<div className="equipment-search"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, categoría o unidad…"/></div></label></div>
  <div className="equipment-results"><p><strong>{filtered.length}</strong> de {systemProducts.length} equipos y servicios</p><span><SlidersHorizontal size={16}/>{canEdit?'Edita todos los datos desde la ficha':'Catálogo de consulta'}</span></div>
  <div className="equipment-table-wrap"><table className="equipment-table"><thead><tr><th>Equipo o servicio</th><th>Unidad de cobro</th><th>Precio unitario</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td className="equipment-name"><strong>{p.name}</strong><div><span>{categoryLabel(p.category)}</span>{p.watts!==null&&p.watts>0&&<span className="equipment-power">{p.watts} Wp</span>}</div></td><td data-label="Unidad">{productUnit(p)}</td><td data-label="Precio unitario" className="equipment-price"><strong className={p.price===null?'is-missing':''}>{p.price===null?'Sin precio':money(p.price)}</strong><small>CLP / {productUnit(p)}</small></td><td className="equipment-row-action"><Button variant="outline" disabled={busy} onClick={()=>open(p)} aria-label={(canEdit?'Editar ':'Ver ')+p.name}><Pencil size={16}/>{canEdit?'Editar':'Ver ficha'}</Button></td></tr>)}</tbody></table></div>
  {!filtered.length&&<div className="equipment-empty"><Package size={30}/><h3>No hay coincidencias</h3><p>Prueba otro nombre o cambia los filtros del catálogo.</p><Button variant="outline" onClick={()=>{setSearch('');setCategory('')}}>Limpiar búsqueda</Button></div>}
  <Dialog open={!!draft} onOpenChange={open=>{if(!open)setDraft(null)}}><DialogContent className="equipment-editor"><DialogHeader><DialogTitle>{isNew?'Agregar equipo o servicio':canEdit?'Editar equipo o servicio':'Ficha del equipo'}</DialogTitle><DialogDescription>Actualiza la ficha y aplica los cambios. Después guarda el catálogo para compartirlos con el equipo.</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();apply()}}><fieldset disabled={!canEdit||busy} className="equipment-editor-grid"><label className="equipment-editor-wide">Nombre del equipo o servicio<Input required maxLength={180} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Sistema<select value={draft.system} onChange={e=>setDraft({...draft,system:e.target.value as Product['system']})}>{systems.map(s=><option key={s} value={s}>{systemNames[s]}</option>)}</select></label><label>Categoría<Input required maxLength={100} list="equipment-category-options" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><datalist id="equipment-category-options">{allCategories.map(c=><option key={c} value={c}/>)}</datalist></label><label>Unidad de cobro<Input required maxLength={50} value={productUnit(draft)} readOnly={productUnit(draft)!==draft.unit||isInstallation(draft)||['TIPO DE ESTRUCTURA','MATERIAL DE TECHO'].includes(draft.category)} onChange={e=>setDraft({...draft,unit:e.target.value})} placeholder="panel, unidad, metro…"/></label><label>Precio unitario (CLP)<Input type="number" min={0} max={1e10} step="any" value={draft.price??''} placeholder="Sin precio confirmado" onChange={e=>setDraft({...draft,price:e.target.value===''?null:Number(e.target.value)})}/></label><label>Potencia (Wp)<Input type="number" min={0} max={2000} step="any" value={draft.watts??''} placeholder="Solo cuando corresponda" onChange={e=>setDraft({...draft,watts:e.target.value===''?null:Number(e.target.value)})}/><small>Para paneles, indica su potencia nominal.</small></label><label>Referencia de origen<Input maxLength={200} value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/><small>Documento, proveedor o ingreso manual.</small></label></fieldset>{error&&<p role="alert" className="equipment-form-error">{error}</p>}<footer className="equipment-editor-footer"><Button type="button" variant="outline" onClick={()=>setDraft(null)}>Cancelar</Button>{canEdit&&<Button disabled={busy} type="submit"><Check size={18}/>{isNew?'Agregar al catálogo':'Aplicar cambios'}</Button>}</footer></form>}</DialogContent></Dialog>
 </section>
}
