'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {money,type SavedQuote} from '@/lib/quote';
import {type HistoryQuote} from '@/lib/quote-history';
import {quoteGroups} from '@/lib/followup';
import {activityTime} from '@/lib/activity';
import {OpenBills} from './workspace-access';
import {FollowupControl} from './followup';
import type {ClientRecord} from './clients';
type Note={id:string;body:string;created_at:string;author:{full_name:string;email:string}|null};
type Detail={quotes:HistoryQuote[];notes:Note[];quoteCount:number;noteCount:number};
export function ClientDetail({client,onClose,onPreview}:{client:ClientRecord;onClose:()=>void;onPreview?:(q:SavedQuote)=>void}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[noteError,setNoteError]=useState('');
 useEffect(()=>{const abort=new AbortController();setError('');fetch(`/api/clients/${client.id}/detail`,{signal:abort.signal}).then(async r=>{const result=await r.json() as Detail&{error?:string};if(!r.ok)throw Error(result.error);return result}).then(setData).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[client.id,refresh]);
 async function saveNote(){setBusy(true);setNoteError('');try{const response=await fetch(`/api/clients/${client.id}/detail`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:note})});const body=await response.json() as {error?:string};if(!response.ok)throw Error(body.error);setNote('');setRefresh(n=>n+1)}catch(e){setNoteError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="client-detail-dialog"><DialogHeader><DialogTitle>{client.details.name}</DialogTitle><DialogDescription>Ficha del cliente · Contacto, proyectos y seguimiento.</DialogDescription></DialogHeader><dl className="client-detail-contact"><div><dt>Contacto</dt><dd>{client.details.email||'Correo pendiente'}<br/>{client.details.phone||'Teléfono pendiente'}</dd></div><div><dt>Ubicación</dt><dd>{client.details.address||'Dirección pendiente'}<br/>{[client.details.commune,client.details.region].filter(Boolean).join(' · ')}</dd></div></dl>{error?<p role="alert">{error} <Button onClick={()=>setRefresh(n=>n+1)}>Reintentar</Button></p>:!data?<p role="status">Cargando la ficha…</p>:<div className="client-detail-columns"><section><h3>Proyectos y documentos</h3>{!data.quotes.length&&<p>Aún no hay propuestas guardadas para este cliente.</p>}{quoteGroups(data.quotes).map(versions=>{const q=versions[0];return <article className="client-project" key={q.projectId||q.id}><div><strong>{q.folio}</strong><span>{money(q.calculation.total)}</span></div><FollowupControl quote={q} onChange={()=>setRefresh(n=>n+1)}/>{onPreview&&<Button variant="outline" onClick={()=>onPreview(q)}>Ver propuesta</Button>}<details><summary>Documentos y revisiones ({versions.length})</summary>{versions.map(version=><div className="client-version" key={version.id}><strong>{version.folio}</strong><p>{activityTime(version.date)}</p>{onPreview&&<Button variant="ghost" onClick={()=>onPreview(version)}>Abrir esta versión</Button>}<OpenBills quoteId={version.id}/></div>)}</details></article>})}{data.quoteCount>data.quotes.length&&<p>Se muestran las últimas {data.quotes.length} versiones. Consulta las anteriores en Cotizaciones.</p>}</section><section><h3>Notas de seguimiento</h3><form className="client-note-form" onSubmit={e=>{e.preventDefault();void saveNote()}}><label htmlFor="client-note">Nueva nota</label><textarea id="client-note" required maxLength={3000} rows={4} placeholder="Acuerdos, necesidades del proyecto o próximos pasos…" value={note} onChange={e=>setNote(e.target.value)}/><Button disabled={busy||!note.trim()} type="submit">{busy?'Guardando…':'Guardar nota'}</Button>{noteError&&<p role="alert">{noteError}</p>}</form><div className="client-notes">{data.notes.map(n=><article key={n.id}><p>{n.body}</p><small>{n.author?.full_name||n.author?.email||'Usuario'} · {activityTime(n.created_at)}</small></article>)}{!data.notes.length&&<p>Las notas quedarán asociadas a su autor y fecha.</p>}{data.noteCount>data.notes.length&&<p>Últimas {data.notes.length} notas. El historial completo permanece en Actividad.</p>}</div></section></div>}</DialogContent></Dialog>
}
