"use client";
import {ClientDetail} from './client-detail';
import type {SavedQuote} from '@/lib/quote';
import {useEffect,useState} from 'react';
import {Search,Users,MapPin,Pencil,Trash2,RotateCcw,Plus,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CustomerLocationFields} from './customer-location';
import {newQuote,quoteSchema,type QuoteInput} from '@/lib/quote';
export type ClientRecord={id:string;details:QuoteInput['customer'];updated_at:string;deleted_at?:string|null};
export type ClientSource={load:(trash:boolean)=>Promise<{clients:ClientRecord[];trashAvailable:boolean}>;save:(id:string|null,details:QuoteInput['customer'])=>Promise<{id:string}>;move:(id:string,action:'trash'|'restore')=>Promise<unknown>};
async function api<T>(path:string,init?:RequestInit){const response=await fetch(path,init);const body=await response.json() as T&{error?:string};if(!response.ok)throw Error(body.error||'No se pudo completar la operación.');return body}
const source:ClientSource={load:trash=>api('/api/clients?trash='+trash),save:(id,details)=>api('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,details})}),move:(id,action)=>api('/api/clients',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action})})};
const key=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');
export function ClientsDirectory({isAdmin,onChange,onQuote,onPreview,dataSource=source}:{onPreview?:(q:SavedQuote)=>void;isAdmin:boolean;onChange?:(client:ClientRecord)=>void;onQuote?:(client:ClientRecord)=>void;dataSource?:ClientSource}){
 const [viewed,setViewed]=useState<ClientRecord|null>(null);
 const [rows,setRows]=useState<ClientRecord[]>([]),[trash,setTrash]=useState(false),[available,setAvailable]=useState(true),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<ClientRecord|null|undefined>(),[details,setDetails]=useState(newQuote().customer),[moving,setMoving]=useState<ClientRecord|null>(null),[formError,setFormError]=useState('');
 async function load(){setLoading(true);setError('');try{const result=await dataSource.load(trash);setRows(result.clients);setAvailable(result.trashAvailable)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');dataSource.load(trash).then(result=>{if(!cancelled){setRows(result.clients);setAvailable(result.trashAvailable)}}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[dataSource,trash]);
 const filtered=rows.filter(row=>key(Object.values(row.details).join(' ')).includes(key(search))).sort((a,b)=>a.details.name.localeCompare(b.details.name,'es'));
 function edit(client:ClientRecord|null){setEditing(client);setDetails(client?{...client.details}:newQuote().customer);setFormError('')}
 async function save(){const parsed=quoteSchema.shape.customer.safeParse(details);if(!parsed.success||!details.name.trim()){setFormError('Completa el nombre y revisa el correo y los datos del cliente.');return}setBusy(true);setFormError('');try{const result=await dataSource.save(editing?.id??null,parsed.data);onChange?.({id:result.id,details:parsed.data,updated_at:new Date().toISOString()});setEditing(undefined);setNotice('Datos del cliente guardados.');await load()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function move(){if(!moving)return;setBusy(true);setFormError('');try{const action=trash?'restore':'trash';await dataSource.move(moving.id,action);onChange?.({...moving,deleted_at:trash?null:new Date().toISOString()});setMoving(null);setNotice(trash?'Cliente restaurado.':'Cliente enviado a la papelera. Sus cotizaciones se conservan.');await load()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 return <section className="clients-directory" aria-label="Directorio de clientes">
  <div className="clients-banner"><div className="clients-banner-icon"><Users size={27}/></div><div><span>RELACIONES COMERCIALES</span><h2>{trash?'Papelera de clientes':'Cada cliente, bien organizado'}</h2><p>{trash?'Recupera un registro cuando lo necesites.':'Corrige sus datos o prepara su próxima propuesta solar.'}</p></div>{!trash&&<Button onClick={()=>edit(null)}><Plus size={17}/>Nuevo cliente</Button>}</div>
  <div className="clients-controls"><div className="clients-segments" role="group" aria-label="Estado de clientes"><button disabled={busy} aria-pressed={!trash} onClick={()=>setTrash(false)}>Clientes activos</button>{isAdmin&&<button disabled={busy} aria-pressed={trash} onClick={()=>setTrash(true)}><Trash2 size={15}/>Papelera</button>}</div><label className="clients-search"><Search size={18}/><input aria-label="Buscar clientes" placeholder="Buscar nombre, correo o comuna…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
  {!available&&<p className="clients-message">Puedes consultar y corregir clientes. La papelera estará disponible al activar la actualización de la base de datos.</p>}
  {notice&&<p role="status" className="clients-message">{notice}</p>}
  {error?<p role="alert" className="clients-message">{error} <button onClick={load}>Reintentar</button></p>:loading?<p role="status" className="clients-empty">Cargando clientes…</p>:<><div className="clients-count">{filtered.length} {filtered.length===1?'cliente':'clientes'}{search?(filtered.length===1?' encontrado':' encontrados'):''}<span>Orden alfabético · {trash?'En papelera':'Activos'}</span></div>{rows.length===500&&<p className="clients-message">Se muestran los 500 registros más recientes.</p>}<div className="clients-grid">{filtered.map(client=><article className="client-record" key={client.id}><div className="client-record-heading"><span className="client-avatar" aria-hidden="true">{client.details.name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><div><h3>{client.details.name}</h3><span>{client.details.email||'Sin correo registrado'}</span></div></div><div className="client-record-contact"><p>{client.details.phone||'Sin teléfono registrado'}</p><p><MapPin size={15}/>{[client.details.commune,client.details.region].filter(Boolean).join(' · ')||'Ubicación pendiente'}</p><p>{client.details.address||'Sin dirección registrada'}</p></div><small>Actualizado el {new Date(client.updated_at).toLocaleDateString('es-CL')}</small><div className="client-record-actions">{trash?<Button variant="outline" disabled={busy||!available} onClick={()=>{setMoving(client);setFormError('')}}><RotateCcw size={16}/>Restaurar</Button>:<><Button variant="outline" onClick={()=>setViewed(client)}>Ver ficha</Button><Button variant="ghost" onClick={()=>edit(client)}><Pencil size={15}/>Editar</Button>{onQuote&&<Button variant="ghost" onClick={()=>onQuote(client)}>Cotizar<ArrowUpRight size={15}/></Button>}{isAdmin&&<Button variant="ghost" className="client-trash" aria-label={'Eliminar a '+client.details.name} disabled={!available} onClick={()=>{setMoving(client);setFormError('')}}><Trash2 size={16}/></Button>}</>}</div></article>)}</div>{!filtered.length&&<div className="clients-empty"><Users size={30}/><h3>{search?'No encontramos coincidencias':trash?'La papelera está vacía':'Aún no hay clientes'}</h3><p>{search?'Prueba con otro nombre, correo o comuna.':trash?'Los clientes que elimines aparecerán aquí.':'Crea un cliente aquí o guárdalo desde el cotizador.'}</p></div>}</>}
  {viewed&&<ClientDetail client={viewed} onClose={()=>setViewed(null)} onPreview={onPreview}/>}
  <Dialog open={editing!==undefined} onOpenChange={open=>{if(!open&&!busy)setEditing(undefined)}}><DialogContent className="client-edit-dialog"><DialogHeader><DialogTitle>{editing?'Editar cliente':'Nuevo cliente'}</DialogTitle><DialogDescription>Las cotizaciones ya guardadas conservan los datos con los que fueron emitidas.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save()}}><div className="client-edit-grid">{(['name','email','phone','address'] as const).map(field=><label key={field}>{({name:'Nombre del cliente',email:'Correo electrónico',phone:'Teléfono',address:'Dirección de suministro'})[field]}<input required={field==='name'} maxLength={field==='name'?150:field==='phone'?40:field==='address'?300:254} type={field==='email'?'email':field==='phone'?'tel':'text'} value={details[field]} onChange={e=>setDetails({...details,[field]:e.target.value})}/></label>)}<CustomerLocationFields region={details.region} commune={details.commune} onChange={location=>setDetails({...details,...location})}/><label>Monto de la boleta (CLP)<input type="number" min="0" max="1000000000" value={details.bill} onChange={e=>setDetails({...details,bill:Number(e.target.value)})}/></label></div>{formError&&<p role="alert">{formError}</p>}<div className="client-dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar cliente'}</Button></div></form></DialogContent></Dialog>
  <Dialog open={!!moving} onOpenChange={open=>{if(!open&&!busy)setMoving(null)}}><DialogContent><DialogHeader><DialogTitle>{trash?'¿Restaurar cliente?':'¿Enviar cliente a la papelera?'}</DialogTitle><DialogDescription>{moving?.details.name}. {trash?'Volverá a estar disponible en el cotizador.':'Se ocultará del listado activo. Puedes recuperarlo; sus cotizaciones y boletas guardadas se conservan.'}</DialogDescription></DialogHeader>{formError&&<p role="alert">{formError}</p>}<div className="client-dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setMoving(null)}>Cancelar</Button><Button disabled={busy} onClick={move}>{busy?'Guardando…':trash?'Restaurar cliente':'Enviar a la papelera'}</Button></div></DialogContent></Dialog>
 </section>;
}
