'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {commercialStates,commercialState,projectKey,type Followup} from '@/lib/followup';
import {chileDate,type HistoryQuote} from '@/lib/quote-history';
export function FollowupControl({quote,onChange}:{quote:HistoryQuote;onChange:()=>void}){
 const [open,setOpen]=useState(false),[status,setStatus]=useState(commercialState(quote)),[date,setDate]=useState(quote.followup?.next_contact??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const state=commercialState(quote),due=quote.followup?.next_contact;const overdue=!!due&&due<chileDate()&&!['accepted','rejected'].includes(state);
 async function save(form:HTMLFormElement){const fields=new FormData(form);setBusy(true);setError('');try{const response=await fetch(`/api/projects/${projectKey(quote)}/followup`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:fields.get('status'),next_contact:fields.get('next_contact')||null,expected:quote.followup?.updated_at??null})});const body=await response.json() as {error?:string};if(!response.ok)throw Error(body.error);setOpen(false);onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="commercial-tracking"><button type="button" className="commercial-state" data-state={state} onClick={()=>{setStatus(state);setDate(due??'');setError('');setOpen(true)}}>{commercialStates[state]}<span>Editar</span></button>{due&&<small data-overdue={overdue}>{overdue?'Contacto pendiente':'Próximo contacto'} · {due.split('-').reverse().join('/')}</small>}<Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogHeader><DialogTitle>Seguimiento comercial</DialogTitle><DialogDescription>{quote.input.customer.name} · Se aplica a todas las revisiones del proyecto.</DialogDescription></DialogHeader><form className="followup-form" onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}><label>Estado<select name="status" value={status} onChange={e=>setStatus(e.target.value as Followup['status'])}>{Object.entries(commercialStates).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Próximo contacto<input name="next_contact" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><p>El estado comercial no confirma un envío, una recepción ni un pago. Registra los envíos en el historial.</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy} type="submit">{busy?'Guardando…':'Guardar seguimiento'}</Button></form></DialogContent></Dialog></div>
}
