"use client";
import {useEffect,useMemo,useState} from 'react';
import {RefreshCw,ArrowUpRight,FileText,Send,Clock,Users,ChevronLeft,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {money} from '@/lib/quote';
import {chileDate,monthLabel,shiftMonth,type HistoryQuote} from '@/lib/quote-history';
import {managementSummary,loadAllHistory} from '@/lib/management-dashboard';
import {memberColors,memberColorStyle} from '@/lib/member-color';
export type DashboardData={quotes:HistoryQuote[];members:{role:string}[]};
export type DashboardSource=(signal:AbortSignal)=>Promise<DashboardData>;
async function json<T>(url:string,signal:AbortSignal){const r=await fetch(url,{signal});const body=await r.json() as T&{error?:string};if(!r.ok)throw Error(body.error||'No se pudo cargar el resumen.');return body}
const source:DashboardSource=async signal=>{const [quotes,team]=await Promise.all([loadAllHistory(offset=>json<{quotes:HistoryQuote[];total:number}>('/api/quote-history?view=list&offset='+offset,signal),signal),json<{members:{role:string}[]}>('/api/members',signal)]);return {quotes,members:team.members}};
export function ManagementDashboard({dataSource=source,onNavigate}:{dataSource?:DashboardSource;onNavigate?:(tab:string)=>void}){
 const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[month,setMonth]=useState(()=>chileDate().slice(0,7));
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');dataSource(controller.signal).then(result=>{if(!controller.signal.aborted)setData(result)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[dataSource,refresh]);
 const summary=useMemo(()=>data?managementSummary(data.quotes,month):null,[data,month]);
 const active=data?.members.filter(m=>['admin','sales'].includes(m.role)).length??0;
 return <section className="management-dashboard"><div className="management-heading"><div><span>Solvex Solar · Gestión comercial</span><h2>{monthLabel(month)}</h2><p>Actividad de las propuestas y del equipo.</p></div><Button variant="outline" aria-label="Mes anterior" disabled={month<='2020-01'} onClick={()=>setMonth(m=>shiftMonth(m,-1))}><ChevronLeft size={16}/></Button><label>Mes<select aria-label="Mes del resumen" value={month.slice(5)} onChange={e=>setMonth(month.slice(0,4)+'-'+e.target.value)}>{['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((name,index)=><option value={String(index+1).padStart(2,'0')} key={name}>{name}</option>)}</select></label><label>Año<select aria-label="Año del resumen" value={month.slice(0,4)} onChange={e=>setMonth(e.target.value+'-'+month.slice(5))}>{Array.from({length:80},(_,i)=>2020+i).map(year=><option key={year}>{year}</option>)}</select></label><Button variant="outline" aria-label="Mes siguiente" disabled={month>='2099-12'} onClick={()=>setMonth(m=>shiftMonth(m,1))}><ChevronRight size={16}/></Button><Button variant="outline" disabled={loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={16}/>Actualizar</Button></div>
 {loading?<p role="status">Cargando el historial completo…</p>:error?<div className="notice" role="alert">{error}</div>:summary&&<><div className="management-kpis">{[{label:'Creadas en el mes',value:summary.created,icon:FileText,detail:'Versiones guardadas'},{label:'Enviadas en el mes',value:summary.sent,icon:Send,detail:'Según fecha de envío registrada'},{label:'Por enviar',value:summary.pending,icon:Clock,detail:'Creadas este mes sin envío registrado'},{label:'Monto de propuestas enviadas',value:money(summary.amount),icon:ArrowUpRight,detail:'Importes completos · no equivale a ventas'}].map(item=><article key={item.label}><item.icon size={20}/><span>{item.label}</span><strong>{item.value}</strong><small>{item.detail}</small></article>)}</div>{summary.unvalued>0&&<p className="notice">{summary.unvalued} propuestas enviadas tienen importes incompletos y no se suman al monto.</p>}
 <div className="management-body"><section className="management-people"><header><h3>Actividad por responsable</h3><span>{summary.people.length} responsables con actividad</span></header>{summary.people.length?<div className="management-table"><table><thead><tr><th>Responsable</th><th>Creadas</th><th>Enviadas</th><th>Monto enviado</th></tr></thead><tbody>{summary.people.map(person=><tr key={person.id}><td><span className="management-person" style={memberColorStyle(memberColors[person.color].id,'')}><i/>{person.name}</span></td><td>{person.created}</td><td>{person.sent}</td><td>{money(person.amount)}</td></tr>)}</tbody></table></div>:<p className="management-empty">No hay cotizaciones creadas ni envíos registrados en este mes.</p>}<p className="help-text">Cada versión guardada cuenta por separado. Se excluyen las cotizaciones en papelera. El envío se registra manualmente y no acredita recepción ni pago.</p>{onNavigate&&<Button variant="outline" onClick={()=>onNavigate('history')}>Ver historial y calendario<ArrowUpRight size={16}/></Button>}</section><aside className="management-team"><Users size={26}/><h3>Equipo habilitado</h3><strong>{active}</strong><p>Usuarios activos actualmente, independiente del mes elegido.</p><p>{data!.members.filter(m=>m.role==='admin').length} administradores con permiso para modificar precios maestros.</p>{onNavigate&&<><Button variant="outline" onClick={()=>onNavigate('members')}>Ver usuarios</Button><Button onClick={()=>onNavigate('quote')}>Abrir cotizador<ArrowUpRight size={16}/></Button></>}</aside></div></>}
 </section>;
}
