'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {activityTime} from '@/lib/activity';
import type {TeamMember} from './members';
type Access={id:string;user_id:string;occurred_at:string;source:'login'|'last_known'};
export function MemberAccess({members}:{members:TeamMember[]}){
 const [open,setOpen]=useState(false),[user,setUser]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState<Access[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setLoading(true);setError('');fetch('/api/members/access?'+new URLSearchParams({user,offset:String(offset)}),{signal:abort.signal}).then(async r=>{const data=await r.json() as {events:Access[];total:number;error?:string};if(!r.ok)throw Error(data.error);return data}).then(data=>{if(!abort.signal.aborted){setRows(data.events);setTotal(data.total)}}).catch(e=>{if(!abort.signal.aborted)setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[open,user,offset,refresh]);
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Historial de accesos</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="access-dialog"><DialogHeader><DialogTitle>Accesos del equipo</DialogTitle><DialogDescription>Inicio de sesión confirmado · Hora de Chile. No indica cuánto tiempo permaneció conectada la persona.</DialogDescription></DialogHeader><label>Usuario<select value={user} onChange={e=>{setUser(e.target.value);setOffset(0)}}><option value="">Todo el equipo</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name||m.email}</option>)}</select></label><p>“Último acceso anterior” conserva la última fecha conocida al activar este historial. Los nuevos inicios de sesión se registran individualmente.</p>{error?<p role="alert">{error}<Button onClick={()=>setRefresh(n=>n+1)}>Reintentar</Button></p>:loading?<p role="status">Consultando accesos…</p>:<div className="access-list">{rows.map(row=><article key={row.id}><div><strong>{members.find(m=>m.id===row.user_id)?.full_name||'Usuario no disponible'}</strong><span>{row.source==='login'?'Inicio de sesión':'Último acceso anterior'}</span></div><time>{activityTime(row.occurred_at)}</time></article>)}{!rows.length&&<p>No hay accesos registrados con este filtro.</p>}</div>}<div className="access-pagination"><Button variant="outline" disabled={loading||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))}>Anterior</Button><span>{Math.min(offset+1,total)}–{Math.min(offset+50,total)} de {total}</span><Button variant="outline" disabled={loading||offset+50>=total} onClick={()=>setOffset(n=>n+50)}>Siguiente</Button></div></DialogContent></Dialog></>
}
