'use client';
import {Input} from '@/components/ui/input';
import {money,type SavedQuote} from '@/lib/quote';
import {newProjection,calculateProjection,projectionContext,projectionIssues,type ProjectionInput} from '@/lib/projection';
export function ProjectionPanel({q,onChange}:{q:SavedQuote;onChange:(p:ProjectionInput)=>void}){
 const p=q.input.projection??newProjection(),issues=projectionIssues(p,q.calculation.total),result=calculateProjection(p,q.calculation.total),approved=p.reviewedFor===projectionContext(q,p)&&issues.length===0&&q.calculation.complete;
 const update=(patch:Partial<ProjectionInput>)=>onChange({...p,...patch,reviewedFor:''});
 const number=(key:'monthlySavings'|'years'|'tariffGrowth'|'degradation'|'annualMaintenance'|'replacementYear'|'replacementCost'|'avoidedKwh'|'emissionFactor',label:string,max:number,nullable=false)=><label>{label}<Input type="number" min={0} max={max} step={key==='years'||key==='replacementYear'?1:'any'} value={p[key]??''} onChange={e=>update({[key]:e.target.value===''&&nullable?null:Math.min(max,Math.max(0,Number(e.target.value)||0))})}/></label>;
 return <section className="projection-editor"><header><span>ANÁLISIS DEL PROYECTO</span><h3>Ahorro y recuperación de inversión</h3><p>Prepara un escenario para el cliente. La potencia instalada y el monto de la boleta no bastan para determinar el ahorro real.</p></header>
 <div className="field-grid">{number('monthlySavings','Ahorro mensual del primer año (CLP)',1e9,true)}{number('years','Horizonte de evaluación (años)',30)}<label className="projection-wide">Fundamento del ahorro<Input maxLength={500} value={p.savingsSource} onChange={e=>update({savingsSource:e.target.value})} placeholder="Energía aprovechada × tarifa evitada, estudio técnico, fecha…"/></label>{number('tariffGrowth','Variación anual de tarifa (%)',20)}{number('degradation','Degradación anual de generación (%)',5)}{number('annualMaintenance','Mantención anual (CLP)',1e9)}{number('replacementCost','Reposición de batería / inversor (CLP)',1e10)}{number('replacementYear','Año de reposición (si aplica)',30,true)}</div>
 <p className="help-text">Para Off Grid verifica la demanda, autonomía y combustible o energía efectivamente reemplazados. La generación solar calculada no equivale automáticamente a ahorro. Incluye mantención y reposiciones previstas; $0 significa que no están contempladas.</p>
 <details><summary>Impacto ambiental (opcional)</summary><p>Usa la energía realmente sustituida y un factor de emisiones documentado. No se calculan equivalencias en árboles sin una metodología aprobada.</p><div className="field-grid">{number('avoidedKwh','Energía evitada del primer año (kWh)',1e8,true)}{number('emissionFactor','Factor de emisiones (kg CO₂ / kWh)',10,true)}<label className="projection-wide">Fuente, año y sistema eléctrico / combustible<Input maxLength={500} value={p.emissionSource} onChange={e=>update({emissionSource:e.target.value})}/></label></div></details>
 {result&&<div className="projection-metrics"><div><small>Ahorro anual inicial, después de costos</small><strong>{money(result.annual)}</strong></div><div><small>Recuperación estimada</small><strong>{result.payback!==null?`${result.payback.toLocaleString('es-CL',{maximumFractionDigits:1})} años`:'Fuera del horizonte'}</strong></div><div><small>Balance a {p.years} años, descontando inversión</small><strong>{money(result.net)}</strong></div></div>}
 {issues.length>0&&<ul className="projection-issues">{issues.map(i=><li key={i}>{i}</li>)}</ul>}
 <label className="installation-toggle"><input type="checkbox" checked={approved} disabled={issues.length>0||!q.calculation.complete} onChange={e=>onChange({...p,reviewedFor:e.target.checked?projectionContext(q,p):''})}/>Revisé los supuestos técnicos y autorizo incluir este escenario en el PDF</label><p className="help-text">{approved?'Se incluirán el resumen financiero, la proyección acumulada y el impacto ambiental si sus datos están completos.':'El PDF no publicará este escenario hasta que esté validado.'} Al cambiar el proyecto o sus supuestos, debes validarlo nuevamente.</p>
 </section>;
}
