'use client';
import {SavingsComparison} from './savings-comparison';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {money,type SavedQuote} from '@/lib/quote';
import {automaticSavings,resolvedProjection,calculateProjection,projectionContext,projectionIssues,type ProjectionInput} from '@/lib/projection';
export function ProjectionPanel({q,onChange}:{q:SavedQuote;onChange:(p:ProjectionInput)=>void}){
 const p=resolvedProjection(q),automatic=automaticSavings(q,p),isAutomatic=p.savingsMode==='automatic',issues=projectionIssues(p,q.calculation.total),result=calculateProjection(p,q.calculation.total),approved=p.reviewedFor===projectionContext(q,p)&&issues.length===0&&q.calculation.complete;
 const update=(patch:Partial<ProjectionInput>)=>onChange({...p,...patch,reviewedFor:''});
 const number=(key:'monthlySavings'|'years'|'tariffGrowth'|'degradation'|'annualMaintenance'|'replacementYear'|'replacementCost'|'avoidedKwh'|'emissionFactor'|'selfConsumptionPercent'|'energyRate'|'exportRate'|'nonEnergyCharges',label:string,max:number,nullable=false)=><label>{label}<Input type="number" min={0} max={max} step={key==='years'||key==='replacementYear'?1:'any'} value={p[key]??''} onChange={e=>update({[key]:e.target.value===''&&nullable?null:Math.min(max,Math.max(0,Number(e.target.value)||0)),...(key==='monthlySavings'?{savingsMode:'manual' as const,savingsSource:isAutomatic?('Ajuste manual del equipo. '+p.savingsSource).slice(0,500):p.savingsSource}:{})})}/></label>;
 const decimal=(v:number)=>v.toLocaleString('es-CL',{maximumFractionDigits:1});
 return <section className="projection-editor"><header><span>ANÁLISIS DEL PROYECTO</span><h3>Ahorro y recuperación de inversión</h3><p>El ahorro se calcula con la generación solar, el consumo y el valor de la energía. Puedes ajustar los supuestos o editar directamente el ahorro mensual.</p></header>
 <div className="savings-mode"><strong>{isAutomatic?'Cálculo automático':'Ahorro editado manualmente'}</strong>{!isAutomatic&&<Button variant="outline" onClick={()=>update({savingsMode:'automatic',selfConsumptionPercent:p.selfConsumptionPercent??70,exportRate:p.exportRate??0})}>Usar cálculo automático</Button>}<span>Editar el ahorro mensual activa el modo manual.</span></div>
 {automatic.result&&<p className="savings-formula">{isAutomatic?"Cálculo mensual":"Referencia automática"}: {decimal(automatic.result.selfConsumed)} kWh × {decimal(automatic.result.rate)} CLP/kWh + {money(automatic.result.exportCredit)} por excedentes = <strong>{money(automatic.result.monthlySavings)}</strong>.</p>}
 <SavingsComparison q={q} projection={p}/>
 <details className="savings-inputs" open={isAutomatic&&!automatic.result}><summary>Datos del cálculo automático</summary>
  <div className="field-grid">{number('selfConsumptionPercent','Generación aprovechada para autoconsumo (%)',100)}{number('energyRate',q.input.system==='OFF GRID'?'Costo de energía reemplazada (CLP/kWh)':'Tarifa de energía editable (CLP/kWh)',1e6,true)}{q.input.system!=='OFF GRID'&&<>{number('nonEnergyCharges','Cargos no evitables de la boleta (CLP)',1e9)}{number('exportRate','Valorización de excedentes (CLP/kWh)',1e6)}</>}</div>
  <p>El 70% es un supuesto inicial de autoconsumo, editable según el uso diurno y las baterías. {q.input.system==='OFF GRID'?'Off Grid requiere el costo de la energía reemplazada; no incluye ingresos por excedentes ni valida autonomía.':'Si dejas la tarifa vacía, se calcula desde la boleta descontando los cargos no evitables. Revisa cargos fijos, deuda e impuestos. Los excedentes no se valorizan hasta ingresar su tarifa.'}</p>
  {automatic.result?<div className="savings-breakdown"><dl><div><dt>Generación promedio mensual</dt><dd>{decimal(automatic.result.monthlyGeneration)} kWh</dd></div><div><dt>Consumo promedio mensual</dt><dd>{decimal(automatic.result.monthlyConsumption)} kWh</dd></div><div><dt>Autoconsumo estimado</dt><dd>{decimal(automatic.result.selfConsumed)} kWh</dd></div><div><dt>Valor de energía utilizado</dt><dd>{decimal(automatic.result.rate)} CLP/kWh{automatic.result.billRate?' · desde boleta':''}</dd></div></dl><p><strong>{money(automatic.result.selfSavings)}</strong> por autoconsumo + <strong>{money(automatic.result.exportCredit)}</strong> por excedentes = <strong>{money(automatic.result.monthlySavings)}/mes</strong>.</p><small>Promedio anual: autoconsumo limitado al consumo del cliente. La producción y el uso real cambian durante el año.</small></div>:<ul className="projection-issues">{automatic.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}
 </details>
 <div className="field-grid">{number('monthlySavings','Ahorro mensual del primer año (CLP)',1e9,true)}{number('years','Horizonte de evaluación (años)',30)}<label className="projection-wide">Fundamento del ahorro<Input maxLength={500} value={p.savingsSource} onChange={e=>update({savingsSource:e.target.value,savingsMode:'manual'})} placeholder="Energía aprovechada × tarifa evitada, estudio técnico, fecha…"/></label>{number('tariffGrowth','Variación anual de tarifa (%)',20)}{number('degradation','Degradación anual de generación (%)',5)}{number('annualMaintenance','Mantención anual (CLP)',1e9)}{number('replacementCost','Reposición de batería / inversor (CLP)',1e10)}{number('replacementYear','Año de reposición (si aplica)',30,true)}</div>
 <p className="help-text">Para Off Grid verifica la demanda, autonomía y combustible o energía efectivamente reemplazados. La generación solar calculada no equivale automáticamente a ahorro. Incluye mantención y reposiciones previstas; $0 significa que no están contempladas.</p>
 <details><summary>Impacto ambiental (opcional)</summary><p>Usa la energía realmente sustituida y un factor de emisiones documentado. No se calculan equivalencias en árboles sin una metodología aprobada.</p><div className="field-grid">{number('avoidedKwh','Energía evitada del primer año (kWh)',1e8,true)}{number('emissionFactor','Factor de emisiones (kg CO₂ / kWh)',10,true)}<label className="projection-wide">Fuente, año y sistema eléctrico / combustible<Input maxLength={500} value={p.emissionSource} onChange={e=>update({emissionSource:e.target.value})}/></label></div></details>
 {result&&<div className="projection-metrics"><div><small>Ahorro anual inicial, después de costos</small><strong>{money(result.annual)}</strong></div><div><small>Recuperación estimada</small><strong>{result.payback!==null?`${result.payback.toLocaleString('es-CL',{maximumFractionDigits:1})} años`:'Fuera del horizonte'}</strong></div><div><small>Balance a {p.years} años, descontando inversión</small><strong>{money(result.net)}</strong></div></div>}
 {issues.length>0&&(!isAutomatic||automatic.result)&&<ul className="projection-issues">{issues.map(i=><li key={i}>{i}</li>)}</ul>}
 <label className="installation-toggle"><input type="checkbox" checked={approved} disabled={issues.length>0||!q.calculation.complete} onChange={e=>onChange({...p,reviewedFor:e.target.checked?projectionContext(q,p):''})}/>Revisé los supuestos técnicos y autorizo incluir este escenario en el PDF</label><p className="help-text">{approved?'Se incluirán el resumen financiero, la proyección acumulada y el impacto ambiental si sus datos están completos.':'El PDF no publicará este escenario hasta que esté validado.'} Al cambiar el proyecto o sus supuestos, debes validarlo nuevamente.</p>
 </section>;
}
