"use client";
import {MapPin,ExternalLink} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {AddressLocation,type LocationLookup} from './address-location';
import type {AddressQuery} from '@/lib/geocoding';
export function ProjectLocation({address,latitude,longitude,onChange,lookup}:{address:AddressQuery;latitude:number|null;longitude:number|null;onChange:(point:{latitude:number|null;longitude:number|null})=>void;lookup?:LocationLookup}){
 const valid=latitude!==null&&longitude!==null&&Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=-56.6&&latitude<=-17&&longitude>=-110&&longitude<=-66;
 return <section className="project-location" aria-label="Georreferencia del proyecto"><div className="project-location-heading"><MapPin size={23}/><div><h3>Ubicación del proyecto</h3><p>Vincula la dirección con el punto donde se instalarán los paneles.</p></div><span>{valid?'Coordenadas cargadas':'Por ubicar'}</span></div><AddressLocation key={JSON.stringify(address)} address={address} lookup={lookup} onChoose={point=>onChange({latitude:point.latitude,longitude:point.longitude})}/><div className="field-grid energy-fields"><label>Latitud<Input aria-label="Latitud del proyecto" type="number" step="any" min={-56.6} max={-17} value={latitude??''} placeholder="Ej. -33.45" onChange={e=>onChange({latitude:e.target.value===''?null:Number(e.target.value),longitude})}/></label><label>Longitud<Input aria-label="Longitud del proyecto" type="number" step="any" min={-110} max={-66} value={longitude??''} placeholder="Ej. -70.66" onChange={e=>onChange({latitude,longitude:e.target.value===''?null:Number(e.target.value)})}/></label></div>{valid?<div className="project-location-result"><div><strong>{latitude.toFixed(6)}, {longitude.toFixed(6)}</strong><p>Revisa que el punto corresponda al techo o terreno de instalación.</p></div><a href={`https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}#map=18/${latitude}/${longitude}`} target="_blank" rel="noreferrer">Revisar en mapa<ExternalLink size={15}/></a></div>:<p className="energy-explanation">Puedes ingresar las coordenadas manualmente si la dirección no tiene coincidencias. Usa un punto dentro de Chile.</p>}<p className="energy-explanation">Si cambias la dirección, comuna o región, se limpiarán las coordenadas para volver a ubicar el proyecto.</p></section>
}
