import {usesSupabase} from '@/lib/supabase/config';
import {workspaceGet,workspacePut} from '@/lib/supabase/api';
import {isDemoDeployment,demoUnavailable} from '@/lib/deployment';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,state} from '@/lib/store';
import {productSchema,settingsSchema} from '@/lib/quote';
import {z} from 'zod';
export async function GET(){if(usesSupabase)return workspaceGet();if(isDemoDeployment)return demoUnavailable();const user=await getChatGPTUser();if(!user)return Response.json({error:'Inicia sesión para guardar y consultar cotizaciones.'},{status:401});try{return Response.json(await state(user.userId));}catch(e){console.error(e);return Response.json({error:'No se pudo cargar el catálogo guardado. Puedes reintentar sin perder tus cambios.'},{status:503});}}
export async function PUT(request:Request){if(usesSupabase)return workspacePut(request);if(isDemoDeployment)return demoUnavailable();const user=await getChatGPTUser();if(!user)return Response.json({error:'Inicia sesión para guardar.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return new Response('Forbidden',{status:403});try{const body=z.object({revision:z.number().int().min(0),products:z.array(productSchema).min(1).max(1000),settings:settingsSchema}).parse(await request.json());if(new Set(body.products.map(p=>p.id)).size!==body.products.length)return Response.json({error:'Hay códigos de producto duplicados.'},{status:400});const payload=JSON.stringify({products:body.products,settings:body.settings});const result=body.revision===0?await database().prepare('INSERT OR IGNORE INTO workspace_state (owner,payload,revision) VALUES (?,?,1)').bind(user.userId,payload).run():await database().prepare('UPDATE workspace_state SET payload = ?, revision = revision + 1 WHERE owner = ? AND revision = ?').bind(payload,user.userId,body.revision).run();if(!result.meta.changes)return Response.json({error:'El catálogo cambió en otra sesión. Recarga antes de guardar.'},{status:409});return Response.json({revision:body.revision+1});}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?'Revisa los valores y el correo de la empresa.':'No se pudo guardar. Tus cambios siguen en pantalla.'},{status:e instanceof z.ZodError?400:503});}}
