'use client';
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';

const statusSchema=z.object({generationEnabled:z.boolean(),remainingAttempts:z.number(),model:z.string()});
const outputSchema=z.object({image:z.string(),mime:z.enum(['image/png','image/jpeg']),generatedAt:z.string()});
const errorSchema=z.object({error:z.string()});
function apiError(data:unknown){const parsed=errorSchema.safeParse(data);return parsed.success?parsed.data.error:'No se pudo completar la solicitud.'}
type Output={image:string;mime:'image/png'|'image/jpeg';generatedAt:string};
export default function SketchLab(){
 const [file,setFile]=useState<File|null>(null),[photo,setPhoto]=useState(''),[panels,setPanels]=useState(10),[style,setStyle]=useState('croquis'),[instructions,setInstructions]=useState(''),[consent,setConsent]=useState(false);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState('Comprueba la conexión antes de generar.'),[error,setError]=useState(''),[ready,setReady]=useState(false),[output,setOutput]=useState<Output|null>(null);
 useEffect(()=>{if(!file){setPhoto('');return}const url=URL.createObjectURL(file);setPhoto(url);return()=>URL.revokeObjectURL(url)},[file]);
 async function check(){setBusy(true);setError('');try{const r=await fetch('/api/ai/sketch',{cache:'no-store'}),raw=await r.json();if(!r.ok)throw Error(apiError(raw));const data=statusSchema.parse(raw);setReady(data.generationEnabled&&data.remainingAttempts>0);setStatus(data.generationEnabled?`${data.model}: conexión verificada. Quedan ${data.remainingAttempts} intentos en esta sesión.`:'Clave y modelo verificados. Generación pausada hasta confirmar facturación y presupuesto.')}catch(e){setReady(false);setError(e instanceof Error?e.message:'No se pudo consultar el estado.')}finally{setBusy(false)}}
 async function generate(){if(!file||!consent||busy)return;setBusy(true);setError('');setOutput(null);try{const body=new FormData();body.set('photo',file);body.set('panels',String(panels));body.set('style',style);body.set('instructions',instructions);body.set('consent','true');const r=await fetch('/api/ai/sketch',{method:'POST',body}),raw=await r.json();if(!r.ok)throw Error(apiError(raw));const data=outputSchema.parse(raw);setOutput(data);setStatus('Imagen generada. Revisa geometría y cantidad de paneles antes de usarla.')}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el croquis.')}finally{setBusy(false)}}
 return <main style={{maxWidth:1100,margin:'36px auto',padding:24}}><h1>Estudio de croquis solares</h1><p>Prueba local con Nano Banana. Genera una referencia visual desde una foto del techo.</p>
 <section className="card" style={{marginTop:24}}><div className="section-heading"><h2>Conexión con Google</h2><Button variant="outline" disabled={busy} onClick={check}>Comprobar conexión</Button></div><p role="status">{status}</p><p>Necesitas una sesión administradora. <a href="/acceso">Ingresar al cotizador</a></p></section>
 <section className="card"><h2>Prepara la referencia</h2><div className="field-grid" style={{marginTop:24}}><label>Fotografía del techo (JPG o PNG, hasta 4 MB)<Input type="file" accept="image/jpeg,image/png" disabled={busy} onChange={e=>{const next=e.target.files?.[0]??null;if(next&&next.size>4*1024*1024){setError('La foto no puede superar 4 MB.');e.target.value='';setFile(null);return}setFile(next);setConsent(false);setOutput(null);setError('')}}/></label><label>Cantidad de paneles<Input type="number" min={1} max={200} value={panels} disabled={busy} onChange={e=>{setPanels(Number(e.target.value));setOutput(null)}}/></label><label>Visualización<select value={style} disabled={busy} onChange={e=>{setStyle(e.target.value);setOutput(null)}}><option value="croquis">Croquis arquitectónico</option><option value="fotomontaje">Fotomontaje sobre la fotografía</option></select></label><label>Indicaciones para el diseño<Textarea maxLength={1200} value={instructions} disabled={busy} onChange={e=>{setInstructions(e.target.value);setOutput(null)}} placeholder="Ubicación deseada, obstáculos, zonas que deben quedar libres…"/></label></div>
 <label style={{display:'flex',flexDirection:'row',alignItems:'flex-start',gap:12,margin:'24px 0'}}><input type="checkbox" checked={consent} disabled={busy} style={{width:20,height:20}} onChange={e=>setConsent(e.target.checked)}/>Puedo compartir esta foto con Google para generar el croquis. No incluye datos personales innecesarios.</label>
 <Button disabled={busy||!ready||!file||!consent||!Number.isInteger(panels)||panels<1||panels>200} onClick={generate}>{busy?'Procesando…':'Generar referencia'}</Button><p style={{marginTop:12}}>Se envían la fotografía y las indicaciones. Cada generación puede tener costo. No se reintenta automáticamente.</p>{error&&<p role="alert" style={{color:'#a53328',marginTop:16}}>{error}</p>}</section>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:24}}>{photo&&<figure className="card"><figcaption>Fotografía original</figcaption><img src={photo} alt="Techo de referencia" style={{width:'100%',height:'auto',marginTop:16}}/></figure>}{output&&<figure className="card"><figcaption>Propuesta visual · requiere revisión</figcaption><img src={`data:${output.mime};base64,${output.image}`} alt="Croquis conceptual generado para revisión" style={{width:'100%',height:'auto',marginTop:16}}/><a href={`data:${output.mime};base64,${output.image}`} download={`solvex-croquis-referencial.${output.mime==='image/png'?'png':'jpg'}`}>Descargar imagen</a></figure>}</div>
 <p>El croquis es referencial: no valida estructura, medidas, orientación ni ingeniería. Esta prueba no guarda imágenes en cotizaciones ni las envía al PDF automáticamente.</p></main>;
}
